### ISSUE TITLE
Austrian background imagery: use basemap.at instead of Geoimage.at

### ISSUE THREAD

**Issue by wernerschka** [osmlab/editor-imagery-index#110]
Hello, I'm using the iD-Openstreetmap editor whose background Imagery are pulled from editor-imagery-index.

I would recommend to use basemap.at (maptype "Orthofoto") Imagery instead of the former Geoimage.at for Austria. For general information about this map, have a look at http://basemap.at/index_en.html
Both are from the same organisation (geoland.at) with the same licensing when using in Openstreetmap. By the way, we already use basemap.at within iD (maptype "Standard", so maybe you should change its name within iD's background map list to "basemap.at Standard")

Basemap.at is the latest, newest free mapping portal of Austrian federal states. It is kind of successor of the former geoland.at WMS-service. Even if the most of the Imagery is the same within both services, the ones of basemap.at are of better image-quality (JPEG-compression, brightness...), in some areas newer (e.g. Vienna), and have less image-artefacts (like zig-zag lines at a straight edge of a building).

The Tilemap-URL template is:
http://maps{s}.wien.gv.at/basemap/bmaporthofoto30cm/normal/google3857/{z}/{y}/{x}.jpeg
where {s} could be 1,2,3,4
Maxzoom level=19

**Comment by wernerschka** [comment]
Thank you tyrasd for adding basemap.at Orthofoto.
Do you have an idea why this Imagery isn't availabe within iD-Editor yet?

**Comment by bhousel** [comment]
> Do you have an idea why this Imagery isn't availabe within iD-Editor yet?

iD 1.8.0 is blocked from being deployed on the openstreetmap.org rails site by an upstream issue that causes the image optimization tool to discard all our icons.  @tomhughes did an awesome job [figuring out the issue and pushing for a quick fix.](https://github.com/openstreetmap/openstreetmap-website/pull/1081#issuecomment-155034014)

In the mean time you can use the release branch of iD that is hosted here: http://openstreetmap.us/iD/release
