### ISSUE TITLE
GSI ortho imagery for Japan

### ISSUE THREAD

**Issue by planemad** [osmlab/editor-imagery-index#111]
Name: Japan GSI Ortho Imagery
source tag: GSImaps/ort
url: http://cyberjapandata.gsi.go.jp/xyz/ort/{z}/{x}/{y}.jpg

Reference: http://wiki.openstreetmap.org/wiki/GSImaps#Ortho_Photo_Tiles

Bing has some serious distortion and should not be used in Japan https://www.openstreetmap.org/user/PlaneMad/diary/36262

**Comment by tyrasd** [comment]
> source: Estonian Land Board orto

really? :jp:

**Comment by planemad** [comment]
@tyrasd woops, corrected!

**Comment by pratikyadav** [comment]
done here

**Comment by mapconcierge** [comment]
Thanks, @planemad !!
That's so useful :-)
