### ISSUE TITLE
source definitions for imagico.de osmim layers

### ISSUE THREAD

**Issue by imagico** [osmlab/editor-imagery-index#112]
I put up source definitions for the [imagico.de OSM images for mapping](http://maps.imagico.de/#osmim) on https://github.com/imagico/osmim-imagery-index.

Included there are files for the individual layers as well as a global file for the aggregate containing all the individual bounding boxes as polygons.

Not sure how this best fits into the structure here so no concrete PR.

**Comment by simonpoole** [comment]
@imagico I intend to include your definitions in https://github.com/simonpoole/osm-layer-index I guess your issue is that they don't fit neatly in to the current continental or world directories?

**Comment by imagico** [comment]
Yes, that is the primary problem.  I could either put the aggregate definition into world although it only covers a small fraction of it - unlike most of the other world layers or the individual images into their respective continental directories based on some data of continental boundaries (which would probably be more complicated for the user).

I also noticed by the way the 'best' property does not really make a lot of sense.  For more than 90 percent of Greenland my images are likely the best currently available but of course there are smaller areas where significantly better imagery is available in Bing - such situations cannot be properly documented with the current data model here.  I have no real solution for this (short of fully mapping image resolution and age in Bing and other variable quality sources) but it is a common problem that people map from the 15 year old base imagery in the Bing and Mapbox layers in areas where no high resolution imagery is available even if newer images exist elsewhere.

**Comment by simonpoole** [comment]
@imagico IMHO I would at least for now simply dump it in a "misc" or whatever directy, I believe everybody that currently uses the index does imagery selection based on coverage bboxes or polygons, so there is no real impact.

WRT quality rating: the current scheme is clearly flawed and I don't see a viable way to improve it by including more detailed data in the source definition itself. I however think that a seperate simple tile based ranking system could work and would be easy to provide both via a service and as a on device offline DB. @Zverik has a nice algorithm for generating ids from tile URLs that could be reused to identify the layer in question.

**Comment by tyrasd** [comment]
> directories

Yes, just put it into a (new) directory if none of the existing ones fit. *misc* doesn't sound too bad.

> 'best' property does not really make a lot of sense

Surely, the flag isn't the ultimate solution to the issue about which imagery to show by default. But it is a first iteration away from the *just use Bing by default everywhere every time* (please correct me if I'm wrong, but as far as I recall is still used/promoted by every editor except iD). Let's discuss improvements in a separate ticket!

Here, the >90% sounds very much like setting the flag would be ok, but as the remaining areas are likely the few (but "important") towns where Bing has high res images, the situation is indeed more complicated. That being said, if you're still unsure if your imagery should or shouldn't use the *best* flag: just leave it away for now and let's revise it once we have better (e.g. zoom-level dependent) solutions in place.
