### ISSUE TITLE
Non-imagery in the list

### ISSUE THREAD

**Issue by pnorman** [osmlab/editor-imagery-index#119]
RIght now we have layers which are purely processed OpenStreetMap data. These layers can't be used in an OpenStreetMap editor to add anything new to OSM, because all the data in them is already in OSM.

What should we do with them?

**Comment by pnorman** [comment]
cc @bhousel

**Comment by bhousel** [comment]
iD doesn't use all of the layers.  We process the file through [this script](https://github.com/openstreetmap/iD/blob/master/data/update_imagery.js).

You can see we blacklist some stuff, rename a few sources, pull in only TMS sources, etc..

**Comment by pnorman** [comment]
per IRC
```
18:14 < pnorman> bhousel: I want to be in a situation where no one is applying layer-specific filtering to the output. filtering out non-TMS, and other projections, that's normal. repacking as a compacter json too
18:15 < bhousel> yeah that seems reasonable.. I'd rather not have that special code in iD either
```
