### ISSUE TITLE
Change name of "OpenStreetMap (Mapnik)" to "OpenStreetMap (Standard)" in index

### ISSUE THREAD

**Issue by SomeoneElseOSM** [osmlab/editor-imagery-index#133]
The "Mapnik" name made sense when the alternative was "Osmarender"; but now that there are multiple Mapnik-based renderings just on osm.org it doesn't make a whole lot of sense.  Users get understandably confused; there's been at least one example of a mapper logging a bug against Mapnik (the piece of software) for a perceived shortcoming in OSM Carto because iD's imagery layer talks about that layer as "OpenStreetMap (Mapnik)".

**Comment by pnorman** [comment]
> The "Mapnik" name made sense when the alternative was "Osmarender"; but now that there are multiple Mapnik-based renderings just on osm.org it doesn't make a whole lot of sense. Users get understandably confused; there's been at least one example of a mapper logging a bug against Mapnik (the piece of software) for a perceived shortcoming in OSM Carto because iD's imagery layer talks about that layer as "OpenStreetMap (Mapnik)".

We no longer track layers which consist of just OSM data.

**Comment by SomeoneElseOSM** [comment]
So presumably iD is doing it's own thing?  I still see "OpenStreetMap (Mapnik)" there.
