### ISSUE TITLE
Raster layers in Brazil

### ISSUE THREAD

**Issue by jfirebaugh** [osmlab/editor-imagery-index#71]
From @astoff in https://github.com/openstreetmap/iD/issues/2256:

>Two extremely useful raster layers have been made available for use in Brazil: "IBGE Mapa de Setores Rurais" and "IBGE Mapa de Setores Urbanos".  They are listed in JOSM's imagery preferences, and the TMS addresses can be found there.

> These options should appear in the background settings panel when editing in Brazil, just like the USGS topographic map appears there when editing in the USA.

**Comment by nighto** [comment]
I'll do it.
