### ISSUE TITLE
editor-imagery expects "template" key, not "url"

### ISSUE THREAD

**Issue by jameslaneconkling** [osmlab/editor-imagery-index#92]
Have been playing around with redeploying iD with a set of custom imagery, as documented in [this blog post](https://www.mapbox.com/blog/customizing-id/) and in the imagery [schema.json](https://github.com/osmlab/editor-imagery-index/blob/gh-pages/schema.json).

Was getting errors until I updated my imagery json file to replace `"url"` with `"template"`, [see here](https://github.com/crowdcover/logging-roads/commit/c65c85f83cfd8b0af3396562a63f3f4103def052#diff-2196918f0d9001b60ebeef1393d8a524).

Is this an error in the schema json [here](https://github.com/osmlab/editor-imagery-index/blob/gh-pages/schema.json#L15), or am I missing something?

**Comment by pnorman** [comment]
schema.json is the authoritative source for the schema. I don't see any reason to expect template to work with editor-imagery-index, and in fact if you try it, it should generate errors with `make check`

**Comment by jameslaneconkling** [comment]
OK, have only tried this with iD.  From the minimal testing I've done, it appears that iD expects `"template"`, not `"url"`.  Sounds like this has to do with iD then, not editor-imagery-index, yeah?  

(the reason I was examining schema.json was b/c it was linked as documentation for instructions on customizing iD: https://www.mapbox.com/blog/customizing-id/)
